# Dependencies
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Melody Kramer
tagline:          'Thinking and working in public'
description:      'A little home for <a href="https://www.twitter.com/mkramer">mkramer</a> on the Internet'
url:              https://melodykramer.github.io
baseurl:          ''

author:
  name:           'Melody Kramer'
  url:            https://twitter.com/mkramer

paginate:         5

github:
  repo:           https://github.com/melodykramer

#gems

gems: [jekyll-paginate, jekyll-gist]
